<?php

namespace App\UI\CLI\Setup;

use App\Security\PasetoHelper;
use ParagonIE\Paseto\Keys\SymmetricKey;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(
    name: 'app:setup:generate-signing-key',
    description: <<<ABCD
        Generates random, symmetric, signing key that will be used to encrypt
        access tokens generated by the json login api endpoint (see: JsonLoginController).
        After generating, but resulted value into the env variable named: ACCESS_TOKEN_SIGNING_KEY
    ABCD

)]
class GenerateSigningKeyCommand extends Command
{
    public function __construct(
        private PasetoHelper $pasetoHelper,
        string $name = null
    ) {
        parent::__construct($name);
    }


    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $output->writeln($this->pasetoHelper->generateRandomAccessTokenSigningKey());
        return self::SUCCESS;
    }
}