<?php

namespace App\UI\CLI\Setup;

use App\Security\PasetoHelper;
use ParagonIE\Paseto\Keys\SymmetricKey;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(
    name: 'app:setup:generate-signing-key',
    description: 'Generates secret api access token signing key'

)]
class GenerateSigningKeyCommand extends Command
{
    public function __construct(
        private PasetoHelper $pasetoHelper,
        string $name = null
    )
    {
        parent::__construct($name);
    }

    protected function configure()
    {
        $this->setHelp(
            <<<ABCD
                Generates random, asymmetric, signing key that is used to sign / encrypt
                access tokens generated by the json login api endpoint (see: JsonLoginController).
                Put the token value into the env variable named: ACCESS_TOKEN_SIGNING_KEY.
                It is secret value - do not expose or commit it.
            ABCD
        );
    }


    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $output->writeln($this->pasetoHelper->generateRandomAccessTokenSigningKey());
        return self::SUCCESS;
    }
}